apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: toad-redis
    chart: toadRedis-11.2.3
    heritage: Helm
    release: cache
  name: cache-toad-redis-master
  namespace: default
spec:
  selector:
    matchLabels:
      app: toad-redis
      release: cache
      role: master
  serviceName: cache-toad-redis-headless
  template:
    metadata:
      annotations:
        checksum/configmap: 7b4bbf31689d5fa99c64497442d2d8845ac93f592898622e5c9dcbd21b734a77
        checksum/health: 6e024f52954d759908ecbee0c2d2605aaf46c3ffcf58eef1874cd61976b5a275
        checksum/secret: 2898a71fd904bccbddc93adc9cd4e129df33a8a6d84e6496122bdc1c029c2f85
      labels:
        app: toad-redis
        chart: toadRedis-11.2.3
        release: cache
        role: master
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - /opt/bitnami/scripts/start-scripts/start-master.sh
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: toad_redis_password
              name: internal
        - name: REDIS_REPLICATION_MODE
          value: master
        - name: REDIS_TLS_ENABLED
          value: "no"
        - name: REDIS_PORT
          value: "6379"
        image: docker.io/bitnami/redis:5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - /health/ping_liveness_local.sh 5
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 6
        name: toad-redis
        ports:
        - containerPort: 6379
          name: redis
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - /health/ping_readiness_local.sh 1
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        securityContext:
          runAsUser: 1001
        volumeMounts:
        - mountPath: /opt/bitnami/scripts/start-scripts
          name: start-scripts
        - mountPath: /health
          name: health
        - mountPath: /data
          name: redis-data
        - mountPath: /opt/bitnami/redis/mounted-etc
          name: config
        - mountPath: /opt/bitnami/redis/etc/
          name: redis-tmp-conf
      securityContext:
        fsGroup: 1001
      serviceAccountName: default
      volumes:
      - configMap:
          defaultMode: 493
          name: cache-toad-redis-scripts
        name: start-scripts
      - configMap:
          defaultMode: 493
          name: cache-toad-redis-health
        name: health
      - configMap:
          name: cache-toad-redis
        name: config
      - emptyDir: {}
        name: redis-data
      - emptyDir: {}
        name: redis-tmp-conf
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates: []
