apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: raptor-redis
    chart: raptorCacheRedis-11.2.3
    heritage: Helm
    release: cache
  name: cache-raptor-redis-master
  namespace: default
spec:
  selector:
    matchLabels:
      app: raptor-redis
      release: cache
      role: master
  serviceName: cache-raptor-redis-headless
  template:
    metadata:
      annotations:
        checksum/configmap: 46db79426a5bfbba05cfea1d18824aca10bfab784905a6e1bae5c216228380a4
        checksum/health: c12f2dd6e78b1cce5c0d9d87a61ff58b580f7fc9207ba99b9cf0b4c5e7bce8d2
        checksum/secret: 5ac488fa201703d94cfe31491c236b9e765704bc1031b29b92687c36a48cbeec
      labels:
        app: raptor-redis
        chart: raptorCacheRedis-11.2.3
        release: cache
        role: master
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - /opt/bitnami/scripts/start-scripts/start-master.sh
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: raptor_redis_password
              name: internal
        - name: REDIS_REPLICATION_MODE
          value: master
        - name: REDIS_TLS_ENABLED
          value: "no"
        - name: REDIS_PORT
          value: "6379"
        image: docker.io/bitnami/redis:5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - /health/ping_liveness_local.sh 5
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 6
        name: raptor-redis
        ports:
        - containerPort: 6379
          name: redis
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - /health/ping_readiness_local.sh 1
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        securityContext:
          runAsUser: 1001
        volumeMounts:
        - mountPath: /opt/bitnami/scripts/start-scripts
          name: start-scripts
        - mountPath: /health
          name: health
        - mountPath: /data
          name: redis-data
        - mountPath: /opt/bitnami/redis/mounted-etc
          name: config
        - mountPath: /opt/bitnami/redis/etc/
          name: redis-tmp-conf
      securityContext:
        fsGroup: 1001
      serviceAccountName: default
      volumes:
      - configMap:
          defaultMode: 493
          name: cache-raptor-redis-scripts
        name: start-scripts
      - configMap:
          defaultMode: 493
          name: cache-raptor-redis-health
        name: health
      - configMap:
          name: cache-raptor-redis
        name: config
      - emptyDir: {}
        name: redis-data
      - emptyDir: {}
        name: redis-tmp-conf
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates: []
