apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: cache
    app.kubernetes.io/name: raptor-redis
  name: cache-raptor-redis-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: master
      app.kubernetes.io/instance: cache
      app.kubernetes.io/name: raptor-redis
  serviceName: cache-raptor-redis-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/component: master
        app.kubernetes.io/instance: cache
        app.kubernetes.io/name: raptor-redis
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: master
                  app.kubernetes.io/instance: cache
                  app.kubernetes.io/name: raptor-redis
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - command:
        - /bin/sh
        - -c
        - redis-server /usr/local/etc/redis/redis.conf --requirepass "${REDIS_PASSWORD}"
          --port "${REDIS_PORT}"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: raptor_redis_password
              name: internal
        - name: REDIS_PORT
          value: "6379"
        image: redis:7.4.11
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - /health/ping_liveness_local.sh 5
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 6
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - /health/ping_readiness_local.sh 1
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits: {}
          requests: {}
        securityContext:
          runAsUser: 1001
        volumeMounts:
        - mountPath: /health
          name: health
        - mountPath: /data
          name: redis-data
        - mountPath: /usr/local/etc/redis
          name: config
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 493
          name: cache-raptor-redis-health
        name: health
      - configMap:
          name: cache-raptor-redis-configuration
        name: config
      - emptyDir: {}
        name: redis-data
  updateStrategy:
    type: RollingUpdate
