apiVersion: v1
data:
  redis-password: ""
kind: Secret
metadata:
  labels:
    app: raptor-redis
    chart: raptorCacheRedis-10.6.12
    heritage: Helm
    release: cache
  name: cache-raptor-redis
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  redis-password: ""
kind: Secret
metadata:
  labels:
    app: toad-redis
    chart: toadRedis-10.6.12
    heritage: Helm
    release: cache
  name: cache-toad-redis
  namespace: default
type: Opaque
---
