apiVersion: v1
data:
  redis-password: Tk9UX1RIRV9SRUFMX1BBU1NXT1JE
kind: Secret
metadata:
  labels:
    app: raptor-redis
    chart: raptorCacheRedis-11.2.3
    heritage: Helm
    release: cache
  name: cache-raptor-redis
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  redis-password: Tk9UX1RIRV9SRUFMX1BBU1NXT1JE
kind: Secret
metadata:
  labels:
    app: toad-redis
    chart: toadRedis-11.2.3
    heritage: Helm
    release: cache
  name: cache-toad-redis
  namespace: default
type: Opaque
---
