apiVersion: v1
data:
  redis-password: MTRHUmVjczM1dg==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: cache
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: raptor-redis
    helm.sh/chart: raptorCacheRedis-14.6.2
  name: cache-raptor-redis
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  redis-password: Tk9UX1RIRV9SRUFMX1BBU1NXT1JE
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: cache
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: toad-redis
    helm.sh/chart: toadRedis-14.6.2
  name: cache-toad-redis
  namespace: default
type: Opaque
---
