---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: cache
    app.kubernetes.io/name: raptor-redis
  name: cache-raptor-redis-headless
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/instance: cache
    app.kubernetes.io/name: raptor-redis
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: cache
    app.kubernetes.io/name: raptor-redis
  name: cache-raptor-redis-master
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: tcp-redis
    nodePort: null
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: cache
    app.kubernetes.io/name: raptor-redis
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: cache
    app.kubernetes.io/name: toad-redis
  name: cache-toad-redis-headless
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/instance: cache
    app.kubernetes.io/name: toad-redis
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: cache
    app.kubernetes.io/name: toad-redis
  name: cache-toad-redis-master
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: tcp-redis
    nodePort: null
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: cache
    app.kubernetes.io/name: toad-redis
  sessionAffinity: None
  type: ClusterIP
---
