---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: raptor-redis
    chart: raptorCacheRedis-10.6.12
    heritage: Helm
    release: cache
  name: cache-raptor-redis-headless
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: raptor-redis
    release: cache
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: raptor-redis
    chart: raptorCacheRedis-10.6.12
    heritage: Helm
    release: cache
  name: cache-raptor-redis-master
  namespace: default
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: raptor-redis
    release: cache
    role: master
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: toad-redis
    chart: toadRedis-10.6.12
    heritage: Helm
    release: cache
  name: cache-toad-redis-headless
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: toad-redis
    release: cache
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: toad-redis
    chart: toadRedis-10.6.12
    heritage: Helm
    release: cache
  name: cache-toad-redis-master
  namespace: default
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: toad-redis
    release: cache
    role: master
  type: ClusterIP
---
