---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: raptor-webhook
  name: raptor-webhook
spec:
  template:
    spec:
      containers:
      - name: raptor-webhook
        env:
          - name: GITHUB_APP_SECRET
            valueFrom:
              secretKeyRef:
                key: github_app_secret
                name: configuration
          - name: S3_PRIVATE_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: bucket_secret_access_key # Uses the existing files bucket for raptor file and image uploads, that toad used before for just files
                name: configuration
          - name: FILE_DOWNLOAD_URL
            valueFrom:
              configMapKeyRef:
                key: zenhub_server_address
                name: toad # Uses the same <hostname>/api endpoint as toad for raptor file uploads
          - name: IS_UPLOAD_FILE_TO_LOCAL
            valueFrom:
              configMapKeyRef:
                name: configuration
                key: local_files
          - name: S3_REGION
            valueFrom:
              configMapKeyRef:
                key: bucket_region
                name: configuration
          - name: S3_BUCKET
            valueFrom:
              configMapKeyRef:
                key: files_bucket_name
                name: configuration
          - name: S3_PRIVATE_BUCKET
            valueFrom:
              configMapKeyRef:
                key: files_bucket_name
                name: configuration
          - name: S3_PRIVATE_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                key: bucket_access_key_id
                name: configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: raptor-admin
  name: raptor-admin
spec:
  template:
    spec:
      containers:
        - name: raptor-admin
          env:
            - name: GITHUB_APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: github_app_secret
                  name: configuration
            - name: S3_PRIVATE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: bucket_secret_access_key # Uses the existing files bucket for raptor file and image uploads, that toad used before for just files
                  name: configuration
            - name: FILE_DOWNLOAD_URL
              valueFrom:
                configMapKeyRef:
                  key: zenhub_server_address
                  name: toad # Uses the same <hostname>/api endpoint as toad for raptor file uploads
            - name: IS_UPLOAD_FILE_TO_LOCAL
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: local_files
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  key: bucket_region
                  name: configuration
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: files_bucket_name
                  name: configuration
            - name: S3_PRIVATE_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: files_bucket_name
                  name: configuration
            - name: S3_PRIVATE_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: bucket_access_key_id
                  name: configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: raptor-api
  name: raptor-api
spec:
  template:
    spec:
      containers:
        - name: raptor-api
          env:
            - name: GITHUB_APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: github_app_secret
                  name: configuration
            - name: S3_PRIVATE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: bucket_secret_access_key # Uses the existing files bucket for raptor file and image uploads, that toad used before for just files
                  name: configuration
            - name: FILE_DOWNLOAD_URL
              valueFrom:
                configMapKeyRef:
                  key: zenhub_server_address
                  name: toad # Uses the same <hostname>/api endpoint as toad for raptor file uploads
            - name: IS_UPLOAD_FILE_TO_LOCAL
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: local_files
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  key: bucket_region
                  name: configuration
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: files_bucket_name
                  name: configuration
            - name: S3_PRIVATE_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: files_bucket_name
                  name: configuration
            - name: S3_PRIVATE_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: bucket_access_key_id
                  name: configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: raptor-cable
  name: raptor-cable
spec:
  template:
    spec:
      containers:
        - name: raptor-cable
          env:
            - name: GITHUB_APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: github_app_secret
                  name: configuration
            - name: S3_PRIVATE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: bucket_secret_access_key # Uses the existing files bucket for raptor file and image uploads, that toad used before for just files
                  name: configuration
            - name: FILE_DOWNLOAD_URL
              valueFrom:
                configMapKeyRef:
                  key: zenhub_server_address
                  name: toad # Uses the same <hostname>/api endpoint as toad for raptor file uploads
            - name: IS_UPLOAD_FILE_TO_LOCAL
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: local_files
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  key: bucket_region
                  name: configuration
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: files_bucket_name
                  name: configuration
            - name: S3_PRIVATE_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: files_bucket_name
                  name: configuration
            - name: S3_PRIVATE_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: bucket_access_key_id
                  name: configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: raptor-sidekiq-worker-default
  name: raptor-sidekiq-worker-default
spec:
  template:
    spec:
      containers:
        - name: raptor-sidekiq-worker
          env:
            - name: GITHUB_APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: github_app_secret
                  name: configuration
            - name: S3_PRIVATE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: bucket_secret_access_key # Uses the existing files bucket for raptor file and image uploads, that toad used before for just files
                  name: configuration
            - name: FILE_DOWNLOAD_URL
              valueFrom:
                configMapKeyRef:
                  key: zenhub_server_address
                  name: toad # Uses the same <hostname>/api endpoint as toad for raptor file uploads
            - name: IS_UPLOAD_FILE_TO_LOCAL
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: local_files
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  key: bucket_region
                  name: configuration
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: files_bucket_name
                  name: configuration
            - name: S3_PRIVATE_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: files_bucket_name
                  name: configuration
            - name: S3_PRIVATE_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: bucket_access_key_id
                  name: configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: raptor-sidekiq-worker
  name: raptor-sidekiq-worker
spec:
  template:
    spec:
      containers:
        - name: raptor-sidekiq-worker
          env:
            - name: GITHUB_APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: github_app_secret
                  name: configuration
            - name: S3_PRIVATE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: bucket_secret_access_key # Uses the existing files bucket for raptor file and image uploads, that toad used before for just files
                  name: configuration
            - name: FILE_DOWNLOAD_URL
              valueFrom:
                configMapKeyRef:
                  key: zenhub_server_address
                  name: toad # Uses the same <hostname>/api endpoint as toad for raptor file uploads
            - name: IS_UPLOAD_FILE_TO_LOCAL
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: local_files
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  key: bucket_region
                  name: configuration
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: files_bucket_name
                  name: configuration
            - name: S3_PRIVATE_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: files_bucket_name
                  name: configuration
            - name: S3_PRIVATE_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: bucket_access_key_id
                  name: configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: raptor-webhook
  name: raptor-webhook
spec:
  template:
    spec:
      containers:
        - name: raptor-webhook
          env:
            - name: GITHUB_APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: github_app_secret
                  name: configuration
            - name: S3_PRIVATE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: bucket_secret_access_key # Uses the existing files bucket for raptor file and image uploads, that toad used before for just files
                  name: configuration
            - name: FILE_DOWNLOAD_URL
              valueFrom:
                configMapKeyRef:
                  key: zenhub_server_address
                  name: toad # Uses the same <hostname>/api endpoint as toad for raptor file uploads
            - name: IS_UPLOAD_FILE_TO_LOCAL
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: local_files
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  key: bucket_region
                  name: configuration
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: files_bucket_name
                  name: configuration
            - name: S3_PRIVATE_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: files_bucket_name
                  name: configuration
            - name: S3_PRIVATE_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: bucket_access_key_id
                  name: configuration
---
apiVersion: batch/v1
kind: Job
metadata:
  name: raptor-db-migrate
spec:
  template:
    spec:
      containers:
      - name: raptor-db-migrate
        env:
          - name: GITHUB_APP_SECRET
            valueFrom:
              secretKeyRef:
                key: github_app_secret
                name: configuration
          - name: S3_PRIVATE_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: bucket_secret_access_key # Uses the existing files bucket for raptor file and image uploads, that toad used before for just files
                name: configuration
          - name: FILE_DOWNLOAD_URL
            valueFrom:
              configMapKeyRef:
                key: zenhub_server_address
                name: toad # Uses the same <hostname>/api endpoint as toad for raptor file uploads
          - name: IS_UPLOAD_FILE_TO_LOCAL
            valueFrom:
              configMapKeyRef:
                name: configuration
                key: local_files
          - name: S3_REGION
            valueFrom:
              configMapKeyRef:
                key: bucket_region
                name: configuration
          - name: S3_BUCKET
            valueFrom:
              configMapKeyRef:
                key: files_bucket_name
                name: configuration
          - name: S3_PRIVATE_BUCKET
            valueFrom:
              configMapKeyRef:
                key: files_bucket_name
                name: configuration
          - name: S3_PRIVATE_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                key: bucket_access_key_id
                name: configuration