apiVersion: batch/v1
kind: Job
metadata:
  name: data-migration
  labels:
    app.kubernetes.io/part-of: zenhub-enterprise
    app.kubernetes.io/application: zenhub
    app.kubernetes.io/instance: zhe-for-k8s
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      imagePullSecrets: # remove-if-custom-registry
        - name: zenhub-docker-registry-credentials # remove-if-custom-registry
      containers:
        - args:
            - bundle
            - exec
            - rake
            - zhe:migrate_4_2
          env:
            - name: MONGO_IS_DOCUMENTDB
              valueFrom:
                configMapKeyRef:
                  key: mongo_is_documentdb
                  name: configuration
            - name: MIGRATIONS_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: pgbouncer_url
                  name: configuration
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: postgres_url
                  name: configuration
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: raptor_redis_password
                  name: internal
            - name: CACHE_REDIS_URL
              value: redis://default:$(REDIS_PASSWORD)@cache-raptor-redis-master:6379/0
            - name: ENTERPRISE_LICENSE_TOKEN
              valueFrom:
                secretKeyRef:
                  key: enterprise_license_token
                  name: configuration
            - name: CABLE_URL
              value: raptor-cable
            - name: GITHUB_APP_ID
              valueFrom:
                configMapKeyRef:
                  key: github_app_id
                  name: configuration
            - name: SAFETY_ASSURED
              value: "1"
            - name: RUBYOPT
              value: -W0
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  key: rails_env
                  name: raptor
            - name: RAILS_LOG_TO_STDOUT
              valueFrom:
                configMapKeyRef:
                  key: rails_log_to_stdout
                  name: raptor
            - name: DATABASE_STATEMENT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: database_statement_timeout
                  name: raptor-migrate
            - name: LOG_JSON
              valueFrom:
                configMapKeyRef:
                  key: log_json
                  name: raptor
            - name: GITHUB_HTML_URL
              valueFrom:
                configMapKeyRef:
                  key: github_html_url
                  name: raptor
            - name: GITHUB_API_URL
              valueFrom:
                configMapKeyRef:
                  key: github_api_url
                  name: raptor
            - name: GITHUB_GRAPHQL_URL
              valueFrom:
                configMapKeyRef:
                  key: github_graphql_url
                  name: raptor
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  key: sentry_dsn
                  name: raptor
            - name: SENTRY_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: sentry_environment
                  name: raptor
            - name: NEW_RELIC_AGENT_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: new_relic_agent_enabled
                  name: raptor
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                configMapKeyRef:
                  key: new_relic_app_name
                  name: raptor
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: s3_access_key_id
                  name: raptor
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: files_bucket_name
                  name: configuration
            - name: S3_PRIVATE_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: s3_private_access_key_id
                  name: raptor
            - name: S3_PRIVATE_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: s3_private_bucket
                  name: raptor
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  key: s3_region
                  name: raptor
            - name: FILES_UPLOAD_PATH
              valueFrom:
                configMapKeyRef:
                  key: files_upload_path
                  name: raptor
                  optional: true
            - name: IS_UPLOAD_FILE_TO_LOCAL
              valueFrom:
                configMapKeyRef:
                  key: is_upload_file_to_local
                  name: raptor
            - name: WEBAPP_URL
              valueFrom:
                configMapKeyRef:
                  key: webapp_url
                  name: raptor
            - name: FILE_DOWNLOAD_URL
              valueFrom:
                configMapKeyRef:
                  key: file_download_url
                  name: raptor
            - name: TOAD_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  key: toad_public_url
                  name: raptor
            - name: OPENAI_ORGANIZATION_ID
              valueFrom:
                configMapKeyRef:
                  key: openai_organization_id
                  name: raptor
            - name: GOOGLE_OAUTH2_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: google_oauth2_client_id
                  name: raptor
            - name: NOTION_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: notion_client_id
                  name: raptor
            - name: SLACK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: slack_client_id
                  name: raptor
            - name: LD_OFFLINE
              valueFrom:
                configMapKeyRef:
                  key: ld_offline
                  name: raptor
            - name: IS_ENTERPRISE
              valueFrom:
                configMapKeyRef:
                  key: is_enterprise
                  name: raptor
            - name: AI_LABELS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: ai_labels_endpoint
                  name: raptor
                  optional: true
            - name: AI_LABELS_MODEL
              valueFrom:
                configMapKeyRef:
                  key: ai_labels_model
                  name: raptor
                  optional: true
            - name: AI_SPRINT_REVIEW_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: ai_sprint_review_endpoint
                  name: raptor
                  optional: true
            - name: AI_SPRINT_REVIEW_MODEL
              valueFrom:
                configMapKeyRef:
                  key: ai_sprint_review_model
                  name: raptor
                  optional: true
            - name: AI_ACCEPTANCE_CRITERIA_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: ai_acceptance_criteria_endpoint
                  name: raptor
                  optional: true
            - name: AI_ACCEPTANCE_CRITERIA_MODEL
              valueFrom:
                configMapKeyRef:
                  key: ai_acceptance_criteria_model
                  name: raptor
                  optional: true
            - name: AZURE_PRIVATE_OPENAI_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: azure_private_openai_endpoint
                  name: raptor
                  optional: true
            - name: AZURE_PRIVATE_OPENAI_ENDPOINT_16K
              valueFrom:
                configMapKeyRef:
                  key: azure_private_openai_endpoint_16k
                  name: raptor
                  optional: true
            - name: AZURE_PRIVATE_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: azure_private_openai_api_key
                  name: raptor
                  optional: true
            - name: CLICKHOUSE_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: clickhouse_enabled
                  name: raptor
                  optional: true
            - name: SIDEKIQ_REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: redis_url
                  name: configuration
            - name: GITHUB_APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: github_app_secret
                  name: configuration
            - name: GRAPHQL_REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: graphql_redis_url
                  name: configuration
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  key: secret_key_base
                  name: internal
            - name: LOCKBOX_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  key: lockbox_master_key
                  name: internal
            - name: GITHUB_TOKEN_VALUE_KEY
              valueFrom:
                secretKeyRef:
                  key: github_token_value_key
                  name: internal
            - name: GITHUB_WEBHOOKS_SECRET
              valueFrom:
                secretKeyRef:
                  key: github_webhooks_secret
                  name: internal
            - name: INTERNAL_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: internal_auth_token
                  name: internal
            - name: INTERNAL_INTEGRATION_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: internal_integration_auth_token
                  name: internal
            - name: LD_SDK_KEY
              valueFrom:
                secretKeyRef:
                  key: ld_sdk_key
                  name: raptor
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  key: new_relic_license_key
                  name: raptor
            - name: TOAD_MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: mongo_url
                  name: configuration
            - name: TOAD_RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  key: rabbitmq_url
                  name: configuration
            - name: RAILS_MAX_THREADS
              valueFrom:
                configMapKeyRef:
                  key: rails_max_threads
                  name: raptor-migrate
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CABLE_REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: cable_redis_url
                  name: configuration
            - name: CABLE_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: cable_allowed_origins
                  name: raptor-migrate
            - name: ACTION_CABLE_WORKERS_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  key: action_cable_workers_pool_size
                  name: raptor-migrate
            - name: WEB_CONCURRENCY
              valueFrom:
                configMapKeyRef:
                  key: web_concurrency
                  name: raptor-migrate
            - name: HUBSPOT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: hubspot_access_token
                  name: raptor
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: s3_secret_access_key
                  name: raptor
            - name: S3_PRIVATE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: s3_private_secret_access_key
                  name: raptor
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: openai_api_key
                  name: raptor
            - name: GOOGLE_OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: google_oauth2_client_secret
                  name: raptor
            - name: NOTION_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: notion_client_secret
                  name: raptor
            - name: SLACK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: slack_client_secret
                  name: raptor
            - name: CLICKHOUSE_URL
              valueFrom:
                secretKeyRef:
                  key: clickhouse_url
                  name: raptor
          image: us.gcr.io/zenhub-public/raptor-backend:zhe-4.4.4
          imagePullPolicy: Always
          name: data-migration
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
            - mountPath: /var/ca-bundle/mongo
              name: mongo-ca-bundle
              readOnly: true
            - mountPath: /var/ca-bundle/postgres
              name: postgres-ca-bundle
              readOnly: true
        # - name: stunnel-redis-sidekiq # Uncomment if you use stunnel sidecar containers to configure stunnel between Zenhub and external Redis
        #   image: us.gcr.io/zenhub-public/stunnel
        #   imagePullPolicy: Always
        #   volumeMounts:
        #     - name: stunnel-redis-sidekiq
        #       mountPath: /etc/stunnel/stunnel.conf
        #       subPath: stunnel.conf
        #     - name: stunnel-redis-sidekiq
        #       mountPath: /etc/stunnel/ca.crt
        #       subPath: ca.crt
        # - name: stunnel-redis-cable
        #   image: us.gcr.io/zenhub-public/stunnel
        #   imagePullPolicy: Always
        #   volumeMounts:
        #     - name: stunnel-redis-cable
        #       mountPath: /etc/stunnel/stunnel.conf
        #       subPath: stunnel.conf
        #     - name: stunnel-redis-cable
        #       mountPath: /etc/stunnel/ca.crt
        #       subPath: ca.crt
      volumes:
        - name: mongo-ca-bundle
          secret:
            secretName: mongo-ca-bundle
        - name: postgres-ca-bundle
          secret:
            secretName: postgres-ca-bundle
        # - name: stunnel-redis-cable # Uncomment if you use configmaps to configure stunnel between Zenhub and external Redis
        #   configMap:
        #     name: stunnel-redis-cable
        # - name: stunnel-redis-sidekiq
        #   configMap:
        #     name: stunnel-redis-sidekiq
      restartPolicy: Never
