apiVersion: batch/v1
kind: Job
metadata:
  name: data-migration
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      imagePullSecrets: # remove-if-custom-registry
        - name: zenhub-docker-registry-credentials # remove-if-custom-registry
      containers:
        - args:
            - bundle
            - exec
            - rake
            - zhe:migrate_3_5
          env:
            - name: MONGO_IS_DOCUMENTDB
              valueFrom:
                configMapKeyRef:
                  key: mongo_is_documentdb
                  name: configuration
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: postgres_url
                  name: configuration
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: raptor_redis_password
                  name: internal
            - name: CACHE_REDIS_URL
              value: redis://default:$(REDIS_PASSWORD)@cache-raptor-redis-master:6379/0
            - name: ENTERPRISE_LICENSE_TOKEN
              valueFrom:
                secretKeyRef:
                  key: enterprise_license_token
                  name: configuration
            - name: CABLE_URL
              value: raptor-cable
            - name: RAILS_MAX_THREADS
              valueFrom:
                configMapKeyRef:
                  key: rails_max_threads
                  name: raptor-admin
            - name: DATABASE_STATEMENT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: database_statement_timeout
                  name: raptor-admin
            - name: ADMIN_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: admin_enabled
                  name: raptor-admin
            - name: ADMIN_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: admin_username
                  name: raptor-admin
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: raptor_admin_password
                  name: internal
            - name: WEB_CONCURRENCY
              valueFrom:
                configMapKeyRef:
                  key: web_concurrency
                  name: raptor-admin
            - name: RUBYOPT
              value: -W0
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  key: rails_env
                  name: raptor
            - name: RAILS_LOG_TO_STDOUT
              valueFrom:
                configMapKeyRef:
                  key: rails_log_to_stdout
                  name: raptor
            - name: LOG_JSON
              valueFrom:
                configMapKeyRef:
                  key: log_json
                  name: raptor
            - name: GITHUB_HTML_URL
              valueFrom:
                configMapKeyRef:
                  key: github_html_url
                  name: raptor
            - name: GITHUB_API_URL
              valueFrom:
                configMapKeyRef:
                  key: github_api_url
                  name: raptor
            - name: GITHUB_GRAPHQL_URL
              valueFrom:
                configMapKeyRef:
                  key: github_graphql_url
                  name: raptor
            - name: NEW_RELIC_AGENT_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: new_relic_agent_enabled
                  name: raptor
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                configMapKeyRef:
                  key: new_relic_app_name
                  name: raptor
            - name: DISABLE_PREPARE_DB
              valueFrom:
                configMapKeyRef:
                  key: disable_prepare_db
                  name: raptor
            - name: GITHUB_WEBHOOK_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: github_webhook_enabled
                  name: raptor
            - name: ZENHUB_WEBHOOK_DOMAIN_V1
              valueFrom:
                configMapKeyRef:
                  key: zenhub_webhook_domain_v1
                  name: raptor
            - name: ZENHUB_WEBHOOK_DOMAIN_V2
              valueFrom:
                configMapKeyRef:
                  key: zenhub_webhook_domain_v2
                  name: raptor
            - name: LD_OFFLINE
              valueFrom:
                configMapKeyRef:
                  key: ld_offline
                  name: raptor
            - name: IS_ENTERPRISE
              valueFrom:
                configMapKeyRef:
                  key: is_enterprise
                  name: raptor
            - name: CABLE_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: cable_allowed_origins
                  name: raptor
            - name: ACTION_CABLE_WORKERS_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  key: action_cable_workers_pool_size
                  name: raptor
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SIDEKIQ_REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: redis_url
                  name: configuration
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  key: secret_key_base
                  name: internal
            - name: LOCKBOX_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  key: lockbox_master_key
                  name: internal
            - name: GITHUB_TOKEN_VALUE_KEY
              valueFrom:
                secretKeyRef:
                  key: github_token_value_key
                  name: internal
            - name: GITHUB_WEBHOOKS_SECRET
              valueFrom:
                secretKeyRef:
                  key: github_webhooks_secret
                  name: internal
            - name: INTERNAL_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: internal_auth_token
                  name: internal
            - name: LD_SDK_KEY
              valueFrom:
                secretKeyRef:
                  key: ld_sdk_key
                  name: raptor
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  key: new_relic_license_key
                  name: raptor
            - name: TOAD_MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: mongo_url
                  name: configuration
            - name: TOAD_RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  key: rabbitmq_url
                  name: configuration
            - name: CABLE_REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: cable_redis_url
                  name: configuration
            - name: GRAPHQL_REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: graphql_redis_url
                  name: configuration
            - name: MIXPANEL_PROJECT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: mixpanel_token
                  name: raptor
            - name: PRODUCT_BOARD_KEY
              valueFrom:
                secretKeyRef:
                  key: product_board_key
                  name: raptor
            - name: HUBSPOT_API_KEY
              valueFrom:
                secretKeyRef:
                  key: hubspot_api_key
                  name: raptor
          image: us.gcr.io/zenhub-public/raptor-backend:zhe-3.5.3
          imagePullPolicy: Always
          name: data-migration
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
            - mountPath: /var/ca-bundle/mongo
              name: mongo-ca-bundle
              readOnly: true
            - mountPath: /var/ca-bundle/postgres
              name: postgres-ca-bundle
              readOnly: true
      volumes:
        - name: mongo-ca-bundle
          secret:
            secretName: mongo-ca-bundle
        - name: postgres-ca-bundle
          secret:
            secretName: postgres-ca-bundle
      restartPolicy: Never
