apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: raptor-api
  name: raptor-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: raptor-api
  template:
    metadata:
      labels:
        app.kubernetes.io/component: raptor-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: raptor-api
              namespaces: []
              topologyKey: kubernetes.io/hostname
            weight: 2
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: raptor-api
              namespaces: []
              topologyKey: topology.kubernetes.io/zone
            weight: 2
      containers:
      - args:
        - bundle
        - exec
        - rails
        - s
        - -b
        - 0.0.0.0
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: postgres_url
              name: configuration
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: raptor_redis_password
              name: internal
        - name: CACHE_REDIS_URL
          value: redis://default:$(REDIS_PASSWORD)@cache-raptor-redis-master:6379/0
        - name: ENTERPRISE_LICENSE_TOKEN
          valueFrom:
            secretKeyRef:
              key: enterprise_license_token
              name: configuration
        - name: CABLE_URL
          value: raptor-cable
        - name: RAILS_MAX_THREADS
          valueFrom:
            configMapKeyRef:
              key: rails_max_threads
              name: raptor-api
        - name: WEB_CONCURRENCY
          valueFrom:
            configMapKeyRef:
              key: web_concurrency
              name: raptor-api
        - name: RUBYOPT
          value: -W0
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              key: rails_env
              name: raptor
        - name: RAILS_LOG_TO_STDOUT
          valueFrom:
            configMapKeyRef:
              key: rails_log_to_stdout
              name: raptor
        - name: LOG_JSON
          valueFrom:
            configMapKeyRef:
              key: log_json
              name: raptor
        - name: GITHUB_HTML_URL
          valueFrom:
            configMapKeyRef:
              key: github_html_url
              name: raptor
        - name: GITHUB_API_URL
          valueFrom:
            configMapKeyRef:
              key: github_api_url
              name: raptor
        - name: GITHUB_GRAPHQL_URL
          valueFrom:
            configMapKeyRef:
              key: github_graphql_url
              name: raptor
        - name: SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              key: sentry_dsn
              name: raptor
        - name: SENTRY_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: sentry_environment
              name: raptor
        - name: NEW_RELIC_AGENT_ENABLED
          valueFrom:
            configMapKeyRef:
              key: new_relic_agent_enabled
              name: raptor
        - name: NEW_RELIC_APP_NAME
          valueFrom:
            configMapKeyRef:
              key: new_relic_app_name
              name: raptor
        - name: DISABLE_PREPARE_DB
          valueFrom:
            configMapKeyRef:
              key: disable_prepare_db
              name: raptor
        - name: GITHUB_WEBHOOK_ENABLED
          valueFrom:
            configMapKeyRef:
              key: github_webhook_enabled
              name: raptor
        - name: ZENHUB_WEBHOOK_DOMAIN_V1
          valueFrom:
            configMapKeyRef:
              key: zenhub_webhook_domain_v1
              name: raptor
        - name: ZENHUB_WEBHOOK_DOMAIN_V2
          valueFrom:
            configMapKeyRef:
              key: zenhub_webhook_domain_v2
              name: raptor
        - name: LD_OFFLINE
          valueFrom:
            configMapKeyRef:
              key: ld_offline
              name: raptor
        - name: IS_ENTERPRISE
          valueFrom:
            configMapKeyRef:
              key: is_enterprise
              name: raptor
        - name: CABLE_ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              key: cable_allowed_origins
              name: raptor
        - name: ACTION_CABLE_WORKERS_POOL_SIZE
          valueFrom:
            configMapKeyRef:
              key: action_cable_workers_pool_size
              name: raptor
        - name: HUBSPOT_PORTAL_ID
          valueFrom:
            configMapKeyRef:
              key: hubspot_portal_id
              name: raptor
        - name: HUBSPOT_PLATFORM_SIGNUP_FORM_GUID
          valueFrom:
            configMapKeyRef:
              key: hubspot_platform_signup_form_guid
              name: raptor
        - name: AUTH_ISSUER_URLS
          valueFrom:
            configMapKeyRef:
              key: auth_issuer_urls
              name: raptor
        - name: AUTH_JWKS_URL
          valueFrom:
            configMapKeyRef:
              key: auth_jwks_url
              name: raptor
        - name: AUTH0_TENANT
          valueFrom:
            configMapKeyRef:
              key: auth0_tenant
              name: raptor
        - name: MAILGUN_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: mailgun_domain
              name: raptor
        - name: WEBAPP_URL
          valueFrom:
            configMapKeyRef:
              key: webapp_url
              name: raptor
        - name: STRIPE_TRIAL_PRICE_ID
          valueFrom:
            configMapKeyRef:
              key: stripe_trial_price_id
              name: raptor
        - name: STRIPE_MONTHLY_PRICE_ID
          valueFrom:
            configMapKeyRef:
              key: stripe_monthly_price_id
              name: raptor
        - name: STRIPE_YEARLY_PRICE_ID
          valueFrom:
            configMapKeyRef:
              key: stripe_yearly_price_id
              name: raptor
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SIDEKIQ_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: redis_url
              name: configuration
        - name: GRAPHQL_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: graphql_redis_url
              name: configuration
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              key: secret_key_base
              name: internal
        - name: LOCKBOX_MASTER_KEY
          valueFrom:
            secretKeyRef:
              key: lockbox_master_key
              name: internal
        - name: GITHUB_TOKEN_VALUE_KEY
          valueFrom:
            secretKeyRef:
              key: github_token_value_key
              name: internal
        - name: GITHUB_WEBHOOKS_SECRET
          valueFrom:
            secretKeyRef:
              key: github_webhooks_secret
              name: internal
        - name: INTERNAL_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: internal_auth_token
              name: internal
        - name: LD_SDK_KEY
          valueFrom:
            secretKeyRef:
              key: ld_sdk_key
              name: raptor
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              key: new_relic_license_key
              name: raptor
        - name: TOAD_MONGO_URL
          valueFrom:
            secretKeyRef:
              key: mongo_url
              name: configuration
        - name: TOAD_RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              key: rabbitmq_url
              name: configuration
        - name: CABLE_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: cable_redis_url
              name: configuration
        - name: MIXPANEL_PROJECT_TOKEN
          valueFrom:
            secretKeyRef:
              key: mixpanel_token
              name: raptor
        - name: PRODUCT_BOARD_KEY
          valueFrom:
            secretKeyRef:
              key: product_board_key
              name: raptor
        - name: HUBSPOT_API_KEY
          valueFrom:
            secretKeyRef:
              key: hubspot_api_key
              name: raptor
        - name: AUTH_MANAGEMENT_API_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: auth_management_api_client_id
              name: raptor
        - name: AUTH_MANAGEMENT_API_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: auth_management_api_client_secret
              name: raptor
        - name: MAILGUN_API_KEY
          valueFrom:
            secretKeyRef:
              key: mailgun_api_key
              name: raptor
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              key: stripe_api_key
              name: raptor
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              key: stripe_webhook_secret
              name: raptor
        image: raptor-backend
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /ping/all
            port: http
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 5
        name: raptor-api
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ping/all
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 350m
            memory: 2000Mi
          requests:
            cpu: 250m
            memory: 1500Mi
