apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: raptor-webhook
  name: raptor-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: raptor-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/component: raptor-webhook
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: raptor-webhook
              namespaces: []
              topologyKey: kubernetes.io/hostname
            weight: 2
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: raptor-webhook
              namespaces: []
              topologyKey: topology.kubernetes.io/zone
            weight: 2
      containers:
      - args:
        - bundle
        - exec
        - rails
        - s
        - -b
        - 0.0.0.0
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: postgres_url
              name: configuration
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: raptor_redis_password
              name: internal
        - name: CACHE_REDIS_URL
          value: redis://default:$(REDIS_PASSWORD)@cache-raptor-redis-master:6379/0
        - name: ENTERPRISE_LICENSE_TOKEN
          valueFrom:
            secretKeyRef:
              key: enterprise_license_token
              name: configuration
        - name: CABLE_URL
          value: raptor-cable
        - name: TOAD_APP_URL
          value: toad-api
        - name: GITHUB_APP_ID
          valueFrom:
            configMapKeyRef:
              key: github_app_id
              name: configuration
        - name: RAILS_MAX_THREADS
          valueFrom:
            configMapKeyRef:
              key: rails_max_threads
              name: raptor-webhook
        - name: WEB_CONCURRENCY
          valueFrom:
            configMapKeyRef:
              key: web_concurrency
              name: raptor-webhook
        - name: RUBYOPT
          value: -W0
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: APP_DEPLOY_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/instance']
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              key: rails_env
              name: raptor
        - name: RAILS_LOG_TO_STDOUT
          valueFrom:
            configMapKeyRef:
              key: rails_log_to_stdout
              name: raptor
        - name: LOG_JSON
          valueFrom:
            configMapKeyRef:
              key: log_json
              name: raptor
        - name: GITHUB_HTML_URL
          valueFrom:
            configMapKeyRef:
              key: github_html_url
              name: raptor
        - name: GITHUB_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: github_html_url
              name: raptor
        - name: GITHUB_API_URL
          valueFrom:
            configMapKeyRef:
              key: github_api_url
              name: raptor
        - name: GITHUB_GRAPHQL_URL
          valueFrom:
            configMapKeyRef:
              key: github_graphql_url
              name: raptor
        - name: SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              key: sentry_dsn
              name: raptor
        - name: SENTRY_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: sentry_environment
              name: raptor
        - name: NEW_RELIC_AGENT_ENABLED
          valueFrom:
            configMapKeyRef:
              key: new_relic_agent_enabled
              name: raptor
        - name: NEW_RELIC_APP_NAME
          valueFrom:
            configMapKeyRef:
              key: new_relic_app_name
              name: raptor
        - name: NEW_RELIC_APPLICATION_LOGGING_ENABLED
          valueFrom:
            configMapKeyRef:
              key: new_relic_application_logging_enabled
              name: raptor
              optional: true
        - name: NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED
          valueFrom:
            configMapKeyRef:
              key: new_relic_application_logging_forwarding_enabled
              name: raptor
              optional: true
        - name: DISABLE_PREPARE_DB
          valueFrom:
            configMapKeyRef:
              key: disable_prepare_db
              name: raptor
        - name: GITHUB_WEBHOOK_ENABLED
          valueFrom:
            configMapKeyRef:
              key: github_webhook_enabled
              name: raptor
        - name: ZENHUB_WEBHOOK_DOMAIN_V2
          valueFrom:
            configMapKeyRef:
              key: zenhub_webhook_domain_v2
              name: raptor
        - name: LD_OFFLINE
          valueFrom:
            configMapKeyRef:
              key: ld_offline
              name: raptor
        - name: IS_ENTERPRISE
          valueFrom:
            configMapKeyRef:
              key: is_enterprise
              name: raptor
        - name: CABLE_ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              key: cable_allowed_origins
              name: raptor
        - name: ACTION_CABLE_WORKERS_POOL_SIZE
          valueFrom:
            configMapKeyRef:
              key: action_cable_workers_pool_size
              name: raptor
        - name: HUBSPOT_PORTAL_ID
          valueFrom:
            configMapKeyRef:
              key: hubspot_portal_id
              name: raptor
        - name: HUBSPOT_PLATFORM_SIGNUP_FORM_GUID
          valueFrom:
            configMapKeyRef:
              key: hubspot_platform_signup_form_guid
              name: raptor
        - name: MIXPANEL_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: mixpanel_project_id
              name: raptor
        - name: HUBSPOT_PAID_USER_FORM_GUID
          valueFrom:
            configMapKeyRef:
              key: hubspot_paid_user_form_guid
              name: raptor
        - name: HUBSPOT_PMF_SURVEY_FORM_GUID
          valueFrom:
            configMapKeyRef:
              key: hubspot_pmf_survey_form_guid
              name: raptor
        - name: HUBSPOT_NPS_SURVEY_FORM_GUID
          valueFrom:
            configMapKeyRef:
              key: hubspot_nps_survey_form_guid
              name: raptor
        - name: HUBSPOT_ZORG_OBJECT_ID
          valueFrom:
            configMapKeyRef:
              key: hubspot_zorg_object_id
              name: raptor
        - name: HUBSPOT_UNLICENSED_MEMBER_ASSOCIATION_TYPE_ID
          valueFrom:
            configMapKeyRef:
              key: hubspot_unlicensed_member_association_type_id
              name: raptor
        - name: HUBSPOT_LICENSED_USER_ASSOCIATION_TYPE_ID
          valueFrom:
            configMapKeyRef:
              key: hubspot_licensed_user_association_type_id
              name: raptor
        - name: HUBSPOT_EXTERNAL_USER_ASSOCIATION_TYPE_ID
          valueFrom:
            configMapKeyRef:
              key: hubspot_external_user_association_type_id
              name: raptor
        - name: HUBSPOT_ADMIN_ASSOCIATION_TYPE_ID
          valueFrom:
            configMapKeyRef:
              key: hubspot_admin_association_type_id
              name: raptor
        - name: AUTH_ISSUER_URLS
          valueFrom:
            configMapKeyRef:
              key: auth_issuer_urls
              name: raptor
        - name: AUTH_JWKS_URL
          valueFrom:
            configMapKeyRef:
              key: auth_jwks_url
              name: raptor
        - name: MAILGUN_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: mailgun_domain
              name: raptor
        - name: WEBAPP_URL
          valueFrom:
            configMapKeyRef:
              key: webapp_url
              name: raptor
        - name: STRIPE_TRIAL_PRICE_ID
          valueFrom:
            configMapKeyRef:
              key: stripe_trial_price_id
              name: raptor
        - name: STRIPE_MONTHLY_PRICE_ID
          valueFrom:
            configMapKeyRef:
              key: stripe_monthly_price_id
              name: raptor
        - name: STRIPE_YEARLY_PRICE_ID
          valueFrom:
            configMapKeyRef:
              key: stripe_yearly_price_id
              name: raptor
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              key: s3_access_key_id
              name: raptor
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              key: s3_bucket
              name: raptor
        - name: S3_PRIVATE_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              key: s3_private_access_key_id
              name: raptor
        - name: S3_PRIVATE_BUCKET
          valueFrom:
            configMapKeyRef:
              key: s3_private_bucket
              name: raptor
        - name: S3_REGION
          valueFrom:
            configMapKeyRef:
              key: s3_region
              name: raptor
        - name: FILES_UPLOAD_PATH
          valueFrom:
            configMapKeyRef:
              key: files_upload_path
              name: raptor
              optional: true
        - name: IS_UPLOAD_FILE_TO_LOCAL
          valueFrom:
            configMapKeyRef:
              key: is_upload_file_to_local
              name: raptor
        - name: FILE_DOWNLOAD_URL
          valueFrom:
            configMapKeyRef:
              key: file_download_url
              name: raptor
        - name: TOAD_PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              key: toad_public_url
              name: raptor
        - name: OPENAI_ORGANIZATION_ID
          valueFrom:
            configMapKeyRef:
              key: openai_organization_id
              name: raptor
        - name: GOOGLE_OAUTH2_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: google_oauth2_client_id
              name: raptor
        - name: NOTION_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: notion_client_id
              name: raptor
        - name: SLACK_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: slack_client_id
              name: raptor
        - name: X_FORWARDED_FOR_TRUSTED_PROXIES
          valueFrom:
            configMapKeyRef:
              key: x_forwarded_for_trusted_proxies
              name: raptor
              optional: true
        - name: CLICKHOUSE_ENABLED
          valueFrom:
            configMapKeyRef:
              key: clickhouse_enabled
              name: raptor
              optional: true
        - name: AI_LABELS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: ai_labels_endpoint
              name: raptor
              optional: true
        - name: AI_LABELS_MODEL
          valueFrom:
            configMapKeyRef:
              key: ai_labels_model
              name: raptor
              optional: true
        - name: AI_SPRINT_REVIEW_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: ai_sprint_review_endpoint
              name: raptor
              optional: true
        - name: AI_SPRINT_REVIEW_MODEL
          valueFrom:
            configMapKeyRef:
              key: ai_sprint_review_model
              name: raptor
              optional: true
        - name: AI_ACCEPTANCE_CRITERIA_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: ai_acceptance_criteria_endpoint
              name: raptor
              optional: true
        - name: AI_ACCEPTANCE_CRITERIA_MODEL
          valueFrom:
            configMapKeyRef:
              key: ai_acceptance_criteria_model
              name: raptor
              optional: true
        - name: AZURE_PRIVATE_OPENAI_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: azure_private_openai_endpoint
              name: raptor
              optional: true
        - name: AZURE_PRIVATE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: azure_private_openai_api_key
              name: raptor
              optional: true
        - name: PROMETHEUS_EXPORTER_HOST
          valueFrom:
            configMapKeyRef:
              key: prometheus_exporter_host
              name: raptor
              optional: true
        - name: SIDEKIQ_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: redis_url
              name: configuration
        - name: GRAPHQL_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: graphql_redis_url
              name: configuration
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              key: secret_key_base
              name: internal
        - name: LOCKBOX_MASTER_KEY
          valueFrom:
            secretKeyRef:
              key: lockbox_master_key
              name: internal
        - name: GITHUB_WEBHOOKS_SECRET
          valueFrom:
            secretKeyRef:
              key: github_webhooks_secret
              name: internal
        - name: TOKEN_VERIFICATION_GITHUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: token_verification_github_access_token
              name: internal
        - name: INTERNAL_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: internal_auth_token
              name: internal
        - name: INTERNAL_INTEGRATION_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: internal_integration_auth_token
              name: internal
        - name: LD_SDK_KEY
          valueFrom:
            secretKeyRef:
              key: ld_sdk_key
              name: raptor
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              key: new_relic_license_key
              name: raptor
        - name: TOAD_MONGO_URL
          valueFrom:
            secretKeyRef:
              key: mongo_url
              name: configuration
        - name: TOAD_RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              key: rabbitmq_url
              name: configuration
        - name: CABLE_REDIS_URL
          valueFrom:
            secretKeyRef:
              key: cable_redis_url
              name: configuration
        - name: MIXPANEL_PROJECT_TOKEN
          valueFrom:
            secretKeyRef:
              key: mixpanel_token
              name: raptor
        - name: MIXPANEL_SERVICE_ACCOUNT_USERNAME
          valueFrom:
            secretKeyRef:
              key: mixpanel_service_account_username
              name: raptor
        - name: MIXPANEL_SERVICE_ACCOUNT_SECRET
          valueFrom:
            secretKeyRef:
              key: mixpanel_service_account_secret
              name: raptor
        - name: FRESHWORKS_API_KEY
          valueFrom:
            secretKeyRef:
              key: freshworks_api_key
              name: raptor
        - name: FRESH_SUCCESS_API_KEY
          valueFrom:
            secretKeyRef:
              key: fresh_success_api_key
              name: raptor
        - name: PRODUCT_BOARD_KEY
          valueFrom:
            secretKeyRef:
              key: product_board_key
              name: raptor
        - name: HUBSPOT_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: hubspot_access_token
              name: raptor
        - name: AUTH_MANAGEMENT_API_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: auth_management_api_client_id
              name: raptor
        - name: AUTH_MANAGEMENT_API_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: auth_management_api_client_secret
              name: raptor
        - name: MAILGUN_API_KEY
          valueFrom:
            secretKeyRef:
              key: mailgun_api_key
              name: raptor
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              key: stripe_api_key
              name: raptor
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              key: stripe_webhook_secret
              name: raptor
        - name: DEVISE_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: devise_jwt_secret_key
              name: raptor
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: s3_secret_access_key
              name: raptor
        - name: S3_PRIVATE_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: s3_private_secret_access_key
              name: raptor
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: openai_api_key
              name: raptor
        - name: GITHUB_APP_SECRET
          valueFrom:
            secretKeyRef:
              key: github_app_secret
              name: configuration
        - name: GLOBAL_GITHUB_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              key: global_github_admin_token
              name: global-github-admin-token-secret
              optional: true
        - name: GOOGLE_OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: google_oauth2_client_secret
              name: raptor
        - name: NOTION_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: notion_client_secret
              name: raptor
        - name: SLACK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: slack_client_secret
              name: raptor
        - name: CLICKHOUSE_URL
          valueFrom:
            secretKeyRef:
              key: clickhouse_url
              name: raptor
        image: raptor-backend
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /ping/all
            port: http
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 5
        name: raptor-webhook
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ping/all
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 300m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 1200Mi
