apiVersion: v1
data:
  admin_enabled: "1"
  admin_username: admin
  database_statement_timeout: 15s
  rails_max_threads: "5"
  web_concurrency: "4"
kind: ConfigMap
metadata:
  name: raptor-admin
---
apiVersion: v1
data:
  rails_max_threads: "5"
  web_concurrency: "4"
kind: ConfigMap
metadata:
  name: raptor-api
---
apiVersion: v1
data:
  action_cable_workers_pool_size: "2"
kind: ConfigMap
metadata:
  name: raptor-cable
---
apiVersion: v1
data:
  action_cable_workers_pool_size: "2"
  cable_allowed_origins: https://$(subdomain_suffix).$(domain_tld), $(github_hostname), null
  database_statement_timeout: 120s
  rails_max_threads: "5"
  web_concurrency: "4"
kind: ConfigMap
metadata:
  name: raptor-migrate
---
apiVersion: v1
data:
  database_statement_timeout: 15s
  rails_max_threads: "5"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: raptor-sidekiq-worker-default
  name: raptor-sidekiq-default
---
apiVersion: v1
data:
  database_statement_timeout: 15s
  rails_max_threads: "5"
kind: ConfigMap
metadata:
  name: raptor-sidekiq
---
apiVersion: v1
data:
  action_cable_workers_pool_size: "2"
  auth_issuer_urls: ""
  auth_jwks_url: ""
  auth0_tenant: ""
  cable_allowed_origins: https://$(subdomain_suffix).$(domain_tld), $(github_hostname), null
  disable_prepare_db: "1"
  github_api_url: $(github_hostname)/api/v3
  github_graphql_url: $(github_hostname)/api/graphql
  github_html_url: $(github_hostname)
  github_webhook_enabled: "true"
  is_enterprise: "true"
  ld_offline: "1"
  log_json: "1"
  new_relic_agent_enabled: "false"
  new_relic_app_name: ""
  rails_env: production
  rails_log_to_stdout: "1"
  sentry_dsn: ""
  sentry_environment: ""
  zenhub_webhook_domain_v1: https://$(subdomain_suffix).$(domain_tld)
  zenhub_webhook_domain_v2: https://$(subdomain_suffix).$(domain_tld)
kind: ConfigMap
metadata:
  name: raptor
---
