apiVersion: v1
data:
  admin_enabled: "1"
  admin_username: admin
  database_statement_timeout: 15s
  rails_max_threads: "5"
  web_concurrency: "4"
kind: ConfigMap
metadata:
  name: raptor-admin
---
apiVersion: v1
data:
  rails_max_threads: "5"
  web_concurrency: "4"
kind: ConfigMap
metadata:
  name: raptor-api
---
apiVersion: v1
data:
  action_cable_workers_pool_size: "2"
kind: ConfigMap
metadata:
  name: raptor-cable
---
apiVersion: v1
data:
  action_cable_workers_pool_size: "2"
  cable_allowed_origins: $(cable_allowed_origins)
  database_statement_timeout: 120s
  rails_max_threads: "5"
  web_concurrency: "4"
kind: ConfigMap
metadata:
  name: raptor-migrate
---
apiVersion: v1
data:
  database_statement_timeout: 15s
  rails_max_threads: "5"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: raptor-sidekiq-worker-default
  name: raptor-sidekiq-default
---
apiVersion: v1
data:
  database_statement_timeout: 15s
  rails_max_threads: "5"
kind: ConfigMap
metadata:
  name: raptor-sidekiq
---
apiVersion: v1
data:
  rails_max_threads: "5"
  web_concurrency: "4"
kind: ConfigMap
metadata:
  name: raptor-webhook
---
apiVersion: v1
data:
  action_cable_workers_pool_size: "2"
  ai_acceptance_criteria_endpoint: http://ai-acceptance-criteria:8000
  ai_acceptance_criteria_model: /models/mistral-7b-openorca.F16.gguf
  ai_labels_endpoint: http://ai-labels:8000
  ai_labels_model: /models/mistral-7b-openorca.F16.gguf
  ai_sprint_review_endpoint: http://ai-sprint-review:8000
  ai_sprint_review_model: /models/mistral-7b-openorca.F16.gguf
  auth_issuer_urls: ""
  auth_jwks_url: ""
  auth0_db_connection_name: ""
  auth0_tenant: ""
  cable_allowed_origins: $(cable_allowed_origins)
  clickhouse_enabled: "false"
  disable_prepare_db: "1"
  file_download_url: $(https_zhe_hostname)/api
  files_upload_path: ""
  github_api_url: $(github_hostname)/api/v3
  github_graphql_url: $(github_hostname)/api/graphql
  github_html_url: $(github_hostname)
  github_webhook_enabled: "true"
  google_oauth2_client_id: ""
  hubspot_paid_user_form_guid: ""
  hubspot_platform_signup_form_guid: ""
  hubspot_portal_id: ""
  hubspot_zorg_member_association_type_id: ""
  hubspot_zorg_object_id: ""
  is_enterprise: "true"
  is_upload_file_to_local: "false"
  ld_offline: "1"
  log_json: "1"
  mailgun_domain: ""
  mixpanel_project_id: ""
  new_relic_agent_enabled: "false"
  new_relic_app_name: ""
  notion_client_id: ""
  openai_organization_id: ""
  rails_env: production
  rails_log_to_stdout: "1"
  s3_access_key_id: ""
  s3_bucket: ""
  s3_private_access_key_id: ""
  s3_private_bucket: ""
  s3_region: ""
  sentry_dsn: ""
  sentry_environment: ""
  slack_client_id: ""
  stripe_monthly_price_id: ""
  stripe_trial_price_id: ""
  stripe_yearly_price_id: ""
  toad_public_url: $(https_zhe_hostname)/api
  webapp_url: $(https_zhe_hostname)
  zenhub_webhook_domain_v2: $(https_zhe_hostname)
kind: ConfigMap
metadata:
  name: raptor
---
