apiVersion: v1
data:
  bucket_secret_access_key: ""
  cable_redis_url: ""
  graphql_redis_url: ""
kind: Secret
metadata:
  name: configuration
---
apiVersion: v1
data: null
kind: Secret
metadata:
  name: internal
---
