---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: admin-ui
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: admin-ui
  name: admin-ui
spec:
  selector:
    app.kubernetes.io/component: admin-ui
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: admin-ui
---
