apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-api
spec:
  template:
    spec:
      containers:
        - name: toad-api
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-cron
spec:
  template:
    spec:
      containers:
        - name: toad-cron
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-websocket
spec:
  template:
    spec:
      containers:
        - name: toad-websocket
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-worker
spec:
  template:
    spec:
      containers:
        - name: toad-worker
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-api
spec:
  template:
    spec:
      containers:
        - name: raptor-api
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-cable
spec:
  template:
    spec:
      containers:
        - name: raptor-cable
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-admin
spec:
  template:
    spec:
      containers:
        - name: raptor-admin
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-sidekiq-worker
spec:
  template:
    spec:
      containers:
        - name: raptor-sidekiq-worker
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-webhook
spec:
  template:
    spec:
      containers:
        - name: raptor-webhook
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraken-webapp
spec:
  template:
    spec:
      containers:
        - name: kraken-webapp
          imagePullPolicy: Always
        - name: kraken-extension
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
spec:
  template:
    spec:
      containers:
        - name: admin-ui
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama
spec:
  template:
    spec:
      containers:
        - name: llama-cpp-python
          imagePullPolicy: Always
