name: "🐛 Bug Report"
description: "If something isn't working as expected 🤔."
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: ⚠️ Please note, that this repository is used to track bugs related to the configuration, documentation and installation of the ZenHub Enterprise On-Premise infrastructure. To report a bug with the ZenHub user-facing application itself, please email us at support@zenhub.com instead.

  - type: dropdown
    attributes:
      label: How are you deploying ZenHub Enterprise On-Premise?
      options:
        - Kubernetes cluster
        - VM (VMWare)
        - VM (AWS)
        - VM (Google Cloud)
    validations:
      required: true

  - type: input
    attributes:
      description: What version of ZenHub Enterprise On-Premise are you having an issue with?
      placeholder: 3.2.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current and expected behavior
      description: A clear and concise description of what problem you're seeing and what you would expect.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Possible solution
      description: "If you have suggestions on a fix for the bug."

  - type: textarea
    attributes:
      label: Additional context
      description: "Add any other context about the problem here. Or a screenshot if applicable."
