name: "🚀 Feature Request"
description: "I have a specific suggestion for ZenHub Enterprise On-Premise!"
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: ⚠️ Please note, that this repository is used to track features related to the configuration, documentation and installation of the ZenHub Enterprise On-Premise infrastructure. To suggest a feature for the ZenHub user-facing application itself, please email us at support@zenhub.com instead.

  - type: textarea
    attributes:
      label: What problem are you trying to solve?
      description: A clear and concise description of what problem you're hoping to solve with this feature.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like to see

  - type: textarea
    attributes:
      label: Describe alternatives you've considered

  - type: textarea
    attributes:
      label: Additional context
      description: "Add any other context about the problem here. Or a screenshot if applicable."
