apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-api
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-cron
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-websocket
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-worker
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-api
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-cable
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-admin
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-sidekiq-worker
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-sidekiq-worker-default
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-webhook
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: batch/v1
kind: Job
metadata:
  name: raptor-db-migrate
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraken-webapp
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsite
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sanitycheck
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama
spec:
  template:
    spec:
      imagePullSecrets:
        - name: zenhub-docker-registry-credentials
