apiVersion: v1
kind: ConfigMap
metadata:
  name: zhe-gw-include-ssl
data:
  include-ssl.conf: |
    listen 443 ssl http2;

    ssl_certificate /data/ssl/nginx-gw.crt;
    ssl_certificate_key /data/ssl/nginx-gw.key;
    ssl_session_tickets off;
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_protocols   TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers   on;
    ssl_ciphers 'AES256-GCM-SHA384 EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA HIGH !RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS';
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
