---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kraken-webapp
  name: kraken-webapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: kraken-webapp
  type: ClusterIP
---
