---
# raptor-api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-api
spec:
  template:
    spec:
      containers:
        - name: raptor-api
          resources:
            requests:
              cpu: 200m
              memory: 500M
            limits:
              cpu: 500m
              memory: 2500M

---
# raptor-cable
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-cable
spec:
  template:
    spec:
      containers:
        - name: raptor-cable
          resources:
            requests:
              cpu: 200m
              memory: 500M
            limits:
              cpu: 500m
              memory: 2500M

---
#toad-api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-api
spec:
  template:
    spec:
      containers:
        - name: toad-api
          resources:
            limits:
              cpu: 500m
              memory: 2500M
            requests:
              cpu: 200m
              memory: 500M

---
# toad-websocket
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-websocket
spec:
  template:
    spec:
      containers:
        - name: toad-websocket
          resources:
            limits:
              cpu: 500m
              memory: 2500M
            requests:
              cpu: 200m
              memory: 500M

---
# raptor-sidekiq-worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-sidekiq-worker
spec:
  template:
    spec:
      containers:
        - name: raptor-sidekiq-worker
          resources:
            requests:
              cpu: 200m
              memory: 500M
            limits:
              cpu: 500m
              memory: 2500M

---
# raptor-admin
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raptor-admin
spec:
  template:
    spec:
      containers:
        - name: raptor-admin
          resources:
            requests:
              cpu: 200m
              memory: 500M
            limits:
              cpu: 500m
              memory: 2500M

---
# toad-cron
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-cron
spec:
  template:
    spec:
      containers:
        - name: toad-cron
          resources:
            limits:
              cpu: 500m
              memory: 2500M
            requests:
              cpu: 200m
              memory: 500M

---
# toad-webhook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-webhook
spec:
  template:
    spec:
      containers:
        - name: toad-webhook
          resources:
            limits:
              cpu: 500m
              memory: 2500M
            requests:
              cpu: 200m
              memory: 500M

---
# toad-worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toad-worker
spec:
  template:
    spec:
      containers:
        - name: toad-worker
          resources:
            limits:
              cpu: 500m
              memory: 2500M
            requests:
              cpu: 200m
              memory: 500M

---
# raptor-db-migrate
apiVersion: batch/v1
kind: Job
metadata:
  name: raptor-db-migrate
spec:
  template:
    spec:
      containers:
        - name: raptor-db-migrate
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 250m
              memory: 750M

---
# nginx-gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
spec:
  template:
    spec:
      containers:
        - name: nginx-gateway
          resources:
            limits:
              cpu: 200m
              memory: 250M
            requests:
              cpu: 50m
              memory: 100M
        - name: monitor
          resources:
            limits:
              cpu: 50m
              memory: 150M
            requests:
              cpu: 50m
              memory: 100M

---
# kraken-webapp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kraken-webapp
spec:
  template:
    spec:
      containers:
        - name: kraken-webapp
          resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 200m
              memory: 200M

---
# admin-ui
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
spec:
  template:
    spec:
      containers:
        - name: admin-ui
          resources:
            limits:
              cpu: 500m
              memory: 500M
            requests:
              cpu: 100m
              memory: 100M
