apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps_v1_deployment_toad-api.yaml
- apps_v1_deployment_toad-cron.yaml
- apps_v1_deployment_toad-webhook.yaml
- apps_v1_deployment_toad-websocket.yaml
- apps_v1_deployment_toad-worker.yaml
- autoscaling_v2beta2_horizontalpodautoscaler_toad-api.yaml
- autoscaling_v2beta2_horizontalpodautoscaler_toad-webhook.yaml
- autoscaling_v2beta2_horizontalpodautoscaler_toad-websocket.yaml
- configmaps.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- role.yaml
- secret.yaml
- service.yaml
