apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: toad-api
  name: toad-automount-sa-token-false-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: toad-cron
  name: toad-automount-sa-token-false-cron
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: toad-websocket
  name: toad-automount-sa-token-false-websocket
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: toad-worker
  name: toad-automount-sa-token-false-worker
---
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: toad-api
  name: toad-api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: toad-api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: toad-websocket
  name: toad-websocket
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: toad-websocket
  sessionAffinity: ClientIP
  type: ClusterIP
---
