apiVersion: v1
data:
  default.conf.template: "upstream webapp {\n  server ${WEBAPP};\n}\n\nupstream api {\n  server ${API};\n}\n\nupstream webhook {\n  server ${WEBHOOK};\n}\n\nupstream action-cable {\n  server ${ACTIONCABLE};\n}\n\nupstream raptor-admin {\n  server ${RAPTORADMIN};\n}\n\nupstream api-socket {\n  hash $remote_addr consistent;\n  server ${SOCKET};\n}\n\ninclude conf.d/include-upstream-bucket.conf;\n\n\nserver {\n    server_tokens off;\n    listen 80;\n\n    include conf.d/include-ssl.conf;\n\n    access_log /var/log/nginx/access.log main;\n    error_log /var/log/nginx/error.log error;\n    server_name _;\n\n    error_page 503 /maintenance.html;\n\n    location /maintenance.html {\n        root /usr/share/nginx/html;\n        internal;\n    }\n\n    location /healthcheck {\n        access_log\toff;\n        error_log\toff;\n        return 200 'ok';\n        add_header Content-Type text/plain;\n    }\n\n    location /status {\n\n        if (-f /data/zhe-monitor/maintenance-status) {\n            return 503;\n        }\n\n        access_log\toff;\n        error_log\toff;\n        return 200 'ok';\n        add_header Content-Type text/plain;\n    }\n\n    location /usage {\n        access_log\toff;\n        error_log\toff;\n        return 404;\n    }\n\n    keepalive_timeout 70;\n\n    add_header Strict-Transport-Security \"max-age=31536000; includeSubdomains\";\n    add_header X-Frame-Options DENY;\n    add_header X-Robots-Tag \"noindex, nofollow, noarchive, nosnippet\";\n    proxy_set_header X-Real-IP $remote_addr;\n    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n    proxy_set_header X-Forwarded-Proto $scheme;\n\n    # Legacy files\n    location ^~ /app/files {\n        rewrite ^/app/files(.*)$ /files$1 permanent;\n    }\n\n    # Legacy workspaces\n    location ^~ /app/workspaces {\n        rewrite ^/app/workspaces(.*)$ /workspaces$1 permanent;\n    }\n\n    include conf.d/include-location-images.conf;\n    include conf.d/include-location-files.conf;\n    include conf.d/include-location-ff-extension.conf;\n\n    location /raptor-admin/ {\n\n        if (-f /data/zhe-monitor/maintenance-status) {\n            return 503;\n        }\n\n        proxy_pass http://raptor-admin/;\n        proxy_http_version 1.1;\n\n        client_max_body_size 30M;\n\n        proxy_redirect off;\n        proxy_set_header Host $http_host;\n        proxy_set_header Connection \"\";\n        proxy_buffering off;\n    }\n\n    location /webhook/ {\n\n        if (-f /data/zhe-monitor/maintenance-status) {\n            return 503;\n        }\n\n        proxy_pass http://webhook/webhook/;\n        proxy_http_version 1.1;\n\n        proxy_redirect off;\n        proxy_next_upstream off;\n        proxy_set_header Host $http_host;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection \"upgrade\";\n        proxy_buffering off;\n    }\n\n    location /api/socket.io {\n        rewrite ^/api/socket.io(.*)$ /socket.io$1;\n    }\n\n    location /socket.io {\n\n        if (-f /data/zhe-monitor/maintenance-status) {\n            return 503;\n        }\n\n        proxy_pass http://api-socket;\n        proxy_http_version 1.1;\n\n        proxy_redirect off;\n        proxy_next_upstream off;\n        proxy_set_header Host $http_host;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection \"upgrade\";\n        proxy_buffering off;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-NginX-Proxy true;\n        real_ip_header X-Real-IP;\n    }\n\n    location /cable/ {\n\n        if (-f /data/zhe-monitor/maintenance-status) {\n            return 503;\n        }\n\n        proxy_pass http://action-cable/cable/;\n        proxy_http_version 1.1;\n\n        proxy_redirect off;\n        proxy_next_upstream off;\n        proxy_set_header Host $http_host;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection \"upgrade\";\n        proxy_buffering off;\n    }\n\n    location /api/ {\n\n        if (-f /data/zhe-monitor/maintenance-status) {\n            return 503;\n        }\n\n        proxy_pass http://api/;\n        proxy_http_version 1.1;\n\n        client_max_body_size 100M;\n\n        proxy_redirect off;\n        proxy_next_upstream off;\n        proxy_set_header Host $http_host;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection \"upgrade\";\n        proxy_buffering off;\n    }\n\n    location /upload/ {\n\n        if (-f /data/zhe-monitor/maintenance-status) {\n            return 503;\n        }\n\n        proxy_pass http://api;\n        proxy_http_version 1.1;\n\n        client_max_body_size 100M;\n\n        proxy_redirect off;\n        proxy_next_upstream off;\n        proxy_set_header Host $http_host;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection \"upgrade\";\n        proxy_buffering off;\n    }\n\n    location / {\n        add_header X-Robots-Tag \"noindex, nofollow, noarchive, nosnippet\";\n\n        if (-f /data/zhe-monitor/maintenance-status) {\n            return 503;\n        }\n\n        proxy_pass http://webapp;\n        proxy_http_version 1.1;\n\n        client_max_body_size 100M;\n\n        proxy_redirect off;\n        proxy_set_header Host $http_host;\n        proxy_set_header Connection \"\";\n        proxy_buffering off;\n    }\n}\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: nginx-gateway
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nginx-gateway
  name: zhe-gw-conf
---
apiVersion: v1
data:
  include-location-ff-extension.conf.template: '# this file will be updated and merged by kustomize'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: nginx-gateway
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nginx-gateway
  name: zhe-gw-include-location-ff-extension
---
apiVersion: v1
data:
  include-location-files.conf.template: '# this file will be updated and merged by kustomize'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: nginx-gateway
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nginx-gateway
  name: zhe-gw-include-location-files
---
apiVersion: v1
data:
  include-location-images.conf.template: '# this file will be updated and merged by kustomize'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: nginx-gateway
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nginx-gateway
  name: zhe-gw-include-location-images
---
apiVersion: v1
data:
  include-ssl.conf: '# this file will be updated and merged by kustomize'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: nginx-gateway
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nginx-gateway
  name: zhe-gw-include-ssl
---
apiVersion: v1
data:
  include-upstream-bucket.conf.template: '# this file will be updated and merged by kustomize'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: nginx-gateway
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nginx-gateway
  name: zhe-gw-include-upstream-bucket
---
apiVersion: v1
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  2048;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '[$time_local] "$request" $status Referrer: "$http_referer" [$proxy_host $upstream_addr] Remote:$remote_addr - RealIP:$realip_remote_addr - FwdFor:$http_x_forwarded_for [$http_user_agent]';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/default.conf;
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: nginx-gateway
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nginx-gateway
  name: zhe-gw-nginx-conf
---
apiVersion: v1
data:
  action-cable: raptor-cable
  api: toad-api
  files: toad-api
  raptoradmin: raptor-admin
  socket: toad-websocket
  webapp: kraken-webapp
  webhook: toad-webhook
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: nginx-gateway
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nginx-gateway
  name: zhe-gw-vars
---
apiVersion: v1
data:
  maintenance.html: "<!DOCTYPE html>\n<html>\n\n  <head>\n    <title>ZenHub Enterprise Maintenance In Progress</title>\n    <style>\n      html {\n        height: 100%\n      }\n      body {\n        background: rgb(15,14,29);\n        background: linear-gradient(315deg, rgba(15,14,29,1) 0%, rgba(29,28,57,1) 22%, rgba(48,65,150,1) 62%, rgba(68,100,228,1) 100%);\n      }\n      #message {  \n        margin-left: auto;\n        margin-right: auto;\n        margin-top: 15%;\n        width: 600px;\n        padding: 10px;\n      }\n      h1, h3 {\n          color: white;\n          font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;\n      }\n    </style>\n  </head>\n\n  <body>\n    <div id=\"message\">\n      <h1>ZenHub (or GitHub) is down for maintenance</h1>\n      <h3>Your ZenHub Enterprise administrators are performing scheduled maintenance. If you have any questions, please contact your ZenHub administrator.</h3>\n    </div>\n  </body>\n  \n</html>\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: nginx-gateway
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nginx-gateway
  name: zhe-maintenance-page
---
apiVersion: v1
data:
  ghe-maintenance-monitor.sh: |-
    #!/bin/bash
    # GitHub Enterprise Maintenance Monitor Service V2 - K8s
    # ZenHub (c)

    DIR_FILE="/data/zhe-monitor/maintenance-status"

    function create_file {
      echo "ZHE Maintenance Enabled: Manual"
      echo "[$(date)] ZHE maintenance Enable" > $DIR_FILE
    }

    function delete_file {
      echo "ZHE Maintenance Disabled: ${responseHistory[*]}"
      rm $DIR_FILE
    }

    ### --- MAIN BLOCK --- ###
    while true; do

      if [ "$MAINTENANCE_MODE" == "TRUE" ]
      then
        create_file

      else

        # make sure the test file is not present
        # if [ -e $DIR_FILE ]; then

        #   rm $DIR_FILE

        # fi

        # Init: Because we need it for later, Reset: Because we no longer need it at the end of the iteration
        goodCode=0;
        maintCode=0;
        response=$(curl -s -o /dev/null -H "Cache-Control: no-cache" -w "%{http_code}" "$GITHUB_SERVER_ADDRESS"/status)

        # Replaces the array values for the last three HTTP codes
        responseHistory[0]=${responseHistory[1]};
        responseHistory[1]=${responseHistory[2]};
        responseHistory[2]=$response;

        for i in "${responseHistory[@]}"; do

          case $i in

            200) let goodCode=goodCode+1;;
            503) let maintCode=maintCode+1;;
            *) echo "The response ($i) is ignored";;

          esac

        done

        echo "G:$goodCode // M:$maintCode // A:${responseHistory[*]}";

        if [ $goodCode -eq 3 ]; then

          # if file exists -> remove file to disable maintenance
          # if file DNE -> don't do anything
          if [ -e $DIR_FILE ]; then

            delete_file

          fi

        elif [ $maintCode -eq 3 ]; then

          # if file exists -> don't do anything
          # if file DNE -> create file to enable maintenance
          if [ ! -e $DIR_FILE ]; then

            create_file

          fi

        fi

      fi

    sleep ${WAITING_TIME:-30};

    done
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: nginx-gateway
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nginx-gateway
  name: zhe-monitor
---
