apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps_v1_deployment_nginx-gateway.yaml
  - configmaps.yaml
  - secret.yaml
  - service.yaml
# patchesStrategicMerge:
#   - tls/set-gateway-tls.yaml

# configMapGenerator:
#   - name: zhe-gw-conf
#     behavior: replace
#     files:
#       - tls/default.conf.template
