apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - zhe3-build.yaml

namePrefix: ""

configurations:
  - var_references.yaml

configMapGenerator:
  - name: zhe-gw-vars
    behavior: merge
    literals:
      - webapp=$(WEBAPP_SERVICE_NAME)
      - api=$(API_SERVICE_NAME)
      - socket=$(SOCKET_SERVICE_NAME)
      - files=$(FILES_SERVICE_NAME)
      - webhook=$(WEBHOOK_SERVICE_NAME)
      - raptoradmin=$(RAPTORADMIN_SERVICE_NAME)

  - name: configuration
    behavior: merge
    literals:
      - raptor_service=$(RAPTOR_SERVICE_NAME)
      - name_prefix=""
      - s3_user_download_expiration=60000
      - s3_user_upload_expiration=300000

vars:
  - name: domain_tld
    objref:
      kind: ConfigMap
      name: configuration
      apiVersion: v1
    fieldref:
      fieldpath: data.domain_tld
  - name: subdomain_suffix
    objref:
      kind: ConfigMap
      name: configuration
      apiVersion: v1
    fieldref:
      fieldpath: data.subdomain_suffix
  - name: name_prefix
    objref:
      kind: ConfigMap
      name: configuration
      apiVersion: v1
    fieldref:
      fieldpath: data.name_prefix
  - name: github_hostname
    objref:
      kind: ConfigMap
      name: configuration
      apiVersion: v1
    fieldref:
      fieldpath: data.github_hostname
  - name: WEBAPP_SERVICE_NAME
    objref:
      kind: Service
      name: kraken-webapp
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: API_SERVICE_NAME
    objref:
      kind: Service
      name: toad-api
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: FILES_SERVICE_NAME
    objref:
      kind: Service
      name: toad-api
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: WEBHOOK_SERVICE_NAME
    objref:
      kind: Service
      name: toad-webhook
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: SOCKET_SERVICE_NAME
    objref:
      kind: Service
      name: toad-websocket
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: RAPTORADMIN_SERVICE_NAME
    objref:
      kind: Service
      name: raptor-admin
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: RAPTOR_SERVICE_NAME
    objref:
      kind: Service
      name: raptor-api
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
