apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: pgbouncer
    app.kubernetes.io/name: pgbouncer
  name: pgbouncer
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: pgbouncer
      app.kubernetes.io/name: pgbouncer
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: pgbouncer
        app.kubernetes.io/name: pgbouncer
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: pgbouncer_url
              name: configuration
        - name: POOL_MODE
          value: transaction
        - name: SERVER_TLS_SSLMODE
          value: verify-full
        - name: SERVER_TLS_CA_FILE
          value: /var/ca-bundle/postgres/postgres-ca.pem
        image: us.gcr.io/zenhub-public/pgbouncer:zhe-4.3.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - killall -INT pgbouncer && sleep 120
        livenessProbe:
          periodSeconds: 60
          tcpSocket:
            port: 5432
        name: pgbouncer
        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1G
          requests:
            cpu: 100m
            memory: 100M
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
