---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: pgbouncer
    app.kubernetes.io/name: pgbouncer
  name: pgbouncer
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app.kubernetes.io/component: pgbouncer
    app.kubernetes.io/name: pgbouncer
  type: ClusterIP
---
